name: bold-curation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python and workflow management
  - python=3.10.*  # More stable for HPC systems
  - snakemake=7.32.*  # Pin to stable version to avoid pandas issues
  - mamba
  
  # Database
  - sqlite=3.39.*  # Slightly older for better HPC compatibility
  
  # Core Perl dependencies (consolidate versions)
  - perl=5.32.*
  - perl-bio-phylo-forest-dbtree
  - perl-text-csv_xs
  - perl-log-log4perl
  - perl-module-load
  - perl-json
  - perl-libwww-perl
  - perl-lwp-protocol-https
  - perl-dbd-sqlite
  - perl-dbi
  - perl-getopt-long
  - perl-time-hires
  
  # Analysis tools
  - hmmer
  - jq
  - curl
  - bc
  - muscle=5.*     # MUSCLE 5.x for sequence alignment
  - mafft=7.*      # Alternative alignment method
  - iqtree=2.*     # Phylogenetic tree construction
  - fasttree=2.*   # Fast phylogenetic tree construction
  - ete3=3.1.*     # Tree manipulation and PDF generation
  - pyqt=5.*       # GUI toolkit required by ETE3
  - xorg-libxext   # X11 extension library for headless operation
  - xorg-libxrender # X11 render extension
 
  
  # OTU clustering tools (pin versions for reproducibility)
  - vsearch=2.22.1
  - cd-hit=4.8.1
  
  # Python packages for compatibility
  - pandas=1.5.*  # Older version to avoid GLIBC issues
  - numpy=1.21.*  # Compatible with pandas 1.5
  - biopython=1.79  # For phylogenetic sequence analysis
  
  # Additional Python packages for statistics reports
  - matplotlib=3.5.*  # Compatible with older numpy/pandas
  - seaborn=0.11.*   # Compatible version
  - psutil=5.8.*     # System monitoring
  - scipy=1.7.*      # Scientific computing (compatible with numpy 1.21)
