config:
BOLD_TSV: resources/test_chironominae_norway_data.tsv
DB_FILE: results/bold.db
SCHEMA: workflow/scripts/schema.sql
INDEXES: workflow/scripts/indexes.sql
LIBS: lib/
PATH: lib/
TAXONOMY_LOADED: results/taxonomy_check.tsv
CRITERIA: "COLLECTION_DATE COLLECTORS COORD COUNTRY REGION SECTOR HAS_IMAGE IDENTIFIER ID_METHOD INSTITUTION MUSEUM_ID PUBLIC_VOUCHER SEQ_QUALITY SITE SPECIES_ID TYPE_SPECIMEN"
DB_FILE_INDEXED: results/bold_indexed.ok
TARGET_LIST: resources/test_chironominae_norway_spec_and_syn.csv
USE_TARGET_LIST: true
PROJECT_NAME: "bold-curation"
TAXON_LEVEL: "species"
KINGDOM: "Animalia"
LOG_LEVEL: "INFO" 
DB_CRITERIA_ADDED: results/criteria_indexed

# Pre-scoring filter options
ENABLE_PRESCORING_FILTER: false  # Master switch
FILTER_TAXA: false
FILTER_TAXA_LIST: ""
FILTER_COUNTRIES: false  
FILTER_COUNTRY_LIST: ""
FILTER_BINS: false  # Include BIN_URI sharing
PRESCORING_FILTERED_OUTPUT: "results/prescoring_filtered.tsv"
