# -------------------------------
# Input data configuration
# -------------------------------
BOLD_TSV: resources/test_data/test_odonata_large.tsv
SCHEMA: workflow/scripts/schema_with_ranks.sql
INDEXES: workflow/scripts/indexes.sql

# Library and path configuration
LIBS: lib/
PATH: lib/

# Logging configuration
LOG_LEVEL: "INFO"

# -------------------------------
# Output directory configuration
# -------------------------------
RESULTS_DIR: "results_phylo_pdf6"  # Default results directory - can be overridden
LOG_DIR: "logs_phylo_pdf6"  # Default log directory - can be overridden

# -------------------------------
# Pre-scoring filter options
# -------------------------------
ENABLE_PRESCORING_FILTER: true  # Master switch true / false
FILTER_TAXA: true  # true / false
FILTER_TAXA_LIST: "resources/test_data/test_odonata_spec.csv"
FILTER_COUNTRIES: true  # true / false
FILTER_COUNTRY_LIST: "resources/countries/test_odonata.txt"
FILTER_BINS: true  # Include BIN_URI sharing true / false
FILTER_SPECIES: true  # Only include records with valid species names (not null, empty, or "None") true / false
MARKER: "COI-5P"  # Specify marker code (e.g., "COI-5P") to filter by marker_code field, or null to disable marker filtering
PRESCORING_FILTERED_OUTPUT: "test_odonata_large_filtered.tsv"  # Filename only - will be placed in RESULTS_DIR

# -------------------------------
# Processing configuration
# -------------------------------
TAXONOMY_CHUNK_SIZE: 10000  # Adjust based on your system's memory
CRITERIA: "COLLECTION_DATE COLLECTORS COORD COUNTRY REGION SECTOR HAS_IMAGE IDENTIFIER ID_METHOD INSTITUTION MUSEUM_ID PUBLIC_VOUCHER SEQ_QUALITY SITE SPECIES_ID TYPE_SPECIMEN"

# OTU Clustering configuration
OTU_CLUSTERING_THRESHOLD: 0.99  # Similarity threshold (99%)
OTU_CLUSTERING_THREADS: 8       # Number of threads for VSEARCH

# -------------------------------
# Target list configuration (after processing)
# -------------------------------
TARGET_LIST: resources/test_data/test_odonata_spec.csv
USE_TARGET_LIST: false
PROJECT_NAME: "bold-curation"
TAXON_LEVEL: "species"
KINGDOM: "Animalia"

# -------------------------------
# Family splitting configuration
# -------------------------------
# Kingdom filtering for export (default: all kingdoms)
# EXPORT_KINGDOMS: ["all"]                    # Export all kingdoms (default)
# EXPORT_KINGDOMS: ["Animalia"]               # Only animals
# EXPORT_KINGDOMS: ["Animalia", "Plantae"]    # Animals and plants
EXPORT_KINGDOMS: ["Animalia"]

# Family size threshold for subfamily splitting (default: 10000)
FAMILY_SIZE_THRESHOLD: 10000 # Split families larger than this by subfamily

# SLURM Job Array Configuration
# Number of parallel jobs in the array (default: 64)
FAMILY_ARRAY_SIZE: 64

# Number of worker threads per job (default: 4)
# Total cores used = FAMILY_ARRAY_SIZE * WORKERS_PER_JOB
WORKERS_PER_JOB: 4

# SLURM Resource Allocation per Job
# Memory per job (default: 8G)
JOB_MEMORY: "8G"

# Maximum time per job (default: 4 hours)
JOB_TIME: "04:00:00"

# Compression settings
COMPRESSION_WORKERS: 16  # Adjust based on your HPC node specs
COMPRESSION_MODE: "family_directories"  # "individual_files" (legacy) or "family_directories" (recommended)
COMPRESS_AFTER_SPLIT: true  # Enable/disable compression
REMOVE_ORIGINAL_DBS: false  # Keep originals for safety initially

# -------------------------------
# Statistics Report Configuration
# ------------------------------
SKIP_DETAILED_TAXONOMY: false     # Skip detailed family-by-order pages for faster execution
STATS_REPORT_FAST_MODE: false    # Use true to specify sub-sampling for very large datasets (>5M records)
STATS_REPORT_SAMPLE_SIZE: 100000 # Sample size for fast mode
STATS_REPORT_MEMORY_MB: 32000    # Memory in MB for Snakemake resource allocation
STATS_REPORT_CPU: 8              # CPU cores for report generation
STATS_REPORT_RUNTIME: 120        # Maximum runtime in minutes (2 hours)

# -------------------------------
# Phylogenetic Analysis Configuration
# -------------------------------
PHYLO_ENABLED: true                    # Master switch to enable/disable phylogenetic analysis

# Output configuration
PHYLO_OUTPUT_DIR: "phylogenies"        # Directory for phylogenetic outputs (relative to RESULTS_DIR)

# Analysis scope and filtering
PHYLO_MIN_OTUS: 3                      # Minimum number of species-BIN combinations required per family
PHYLO_MAX_FAMILIES: 0                  # Maximum families to process (0 = all families, number = limit for testing)
PHYLO_KINGDOMS: ["Animalia"]           # Kingdoms to process: ["all"] or specific kingdoms like ["Animalia", "Plantae"]

# Parallel processing configuration (SLURM Job Arrays)
PHYLO_NUM_JOBS: 50                     # Number of SLURM array jobs
PHYLO_FAMILIES_PER_JOB: null           # Fixed families per job (null = auto-distribute evenly)
PHYLO_MAX_CONCURRENT: 10               # Maximum concurrent jobs (controls %N in array)

# SLURM resource allocation per job
PHYLO_JOB_MEMORY: "32G"                # Memory per job
PHYLO_JOB_TIME: "24:00:00"             # Time limit per job (HH:MM:SS)
PHYLO_PARTITION: "day"                # SLURM partition to use

# Analysis methods
PHYLO_ALIGNMENT_METHOD: "mafft"        # Alignment method: "mafft" or "muscle"
PHYLO_TREE_METHOD: "fasttree"          # Tree method: "fasttree" or "iqtree"
PHYLO_BOOTSTRAP: 1000                  # Bootstrap replicates (for IQ-TREE only)
PHYLO_NUM_OUTGROUPS: 3                 # Number of outgroup sequences per tree

# Output options
PHYLO_GENERATE_PDFS: true              # Generate tree visualization PDFs with BAGS grades
PHYLO_CLEANUP_INTERMEDIATES: true      # Clean up intermediate files to save space

# Advanced configuration (optional)
PHYLO_SELECTION_STRATEGY: "best_quality"  # Representative selection: "longest", "random", "best_quality"

# Custom parameters for phylogenetic software (optional overrides)
# These override the optimized defaults when specified
PHYLO_CUSTOM_PARAMETERS:
  mafft: ["--quiet", "--adjustdirection", "--op", "10.0", "--ep", "1.0", "--maxiterate", "1000"]  # High gap penalties for COI - discourages spurious gaps
  fasttree: []                    # Additional FastTree parameters: ["-slow"] for higher accuracy
  iqtree: ["--fast", "-m", "GTR+I+G"]   # Fast mode with GTR+I+G model for COI sequences

# Note: Output paths are dynamically constructed using RESULTS_DIR and LOG_DIR 
# in the Snakefile helper functions. Directories are created automatically.