# MINIMAL CONFIGURATION FOR PARALLEL PHYLOGENETIC ANALYSIS
# ========================================================
# Add these settings to your config/config.yml file

# -------------------------------
# Basic Phylogenetic Analysis Settings (REQUIRED)
# -------------------------------
PHYLO_ENABLED: true                    # Set to true to enable phylogenetic analysis
PHYLO_MIN_OTUS: 3                      # Minimum species-BIN combinations per family
PHYLO_KINGDOMS: ["Animalia"]           # Which kingdoms to process

# -------------------------------
# Parallel Processing Settings (REQUIRED)
# -------------------------------
PHYLO_NUM_JOBS: 50                     # Number of SLURM array jobs (adjust based on your cluster)
PHYLO_MAX_CONCURRENT: 10               # Maximum concurrent jobs (prevents overwhelming queue)

# -------------------------------
# Resource Allocation (RECOMMENDED)
# -------------------------------
PHYLO_JOB_MEMORY: "32G"                # Memory per job (increase if families are very large)
PHYLO_JOB_TIME: "24:00:00"             # Time limit per job
PHYLO_PARTITION: "week"                # SLURM partition (adjust for your cluster)

# -------------------------------
# Analysis Methods (OPTIONAL - defaults shown)
# -------------------------------
PHYLO_ALIGNMENT_METHOD: "mafft"        # "mafft" (faster) or "muscle" (sometimes more accurate)
PHYLO_TREE_METHOD: "fasttree"          # "fasttree" (faster) or "iqtree" (more accurate)
PHYLO_NUM_OUTGROUPS: 3                 # Number of outgroup sequences per tree
PHYLO_GENERATE_PDFS: true              # Generate visualization PDFs (recommended)

# -------------------------------
# Testing/Development (OPTIONAL)
# -------------------------------
# PHYLO_MAX_FAMILIES: 10               # Uncomment to limit families for testing
# PHYLO_FAMILIES_PER_JOB: 2            # Uncomment to force specific batch sizes

# ========================================================
# CLUSTER-SPECIFIC ADJUSTMENTS
# ========================================================

# For smaller clusters or limited resources:
# -----------------------------------------
# PHYLO_NUM_JOBS: 20
# PHYLO_MAX_CONCURRENT: 5
# PHYLO_JOB_MEMORY: "16G"

# For high-performance clusters:
# -----------------------------
# PHYLO_NUM_JOBS: 100
# PHYLO_MAX_CONCURRENT: 30
# PHYLO_JOB_MEMORY: "64G"
# PHYLO_TREE_METHOD: "iqtree"
# PHYLO_BOOTSTRAP: 1000

# For testing with small subset:
# ------------------------------
# PHYLO_MAX_FAMILIES: 5
# PHYLO_NUM_JOBS: 3
# PHYLO_FAMILIES_PER_JOB: 2
